name: Build
run-name: ${{ gitea.actor }} is running Gitea Actions 🚀

on:
  push:
    branches:
      - main 
env:
  GITEA_INSTANCE_URL: http://gitea.home
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: kirom/sys-tracker
          token: ${{ secrets.GITEA_TOKEN }}
          fetch-depth: 1
          server_url: http://gitea.home

      - name: Display Environment Variables
        run: cat .env

      - name: Generate Requirements File
        run: pip freeze > requirements.txt

      - name: Docker Login
        run: echo "${{ secrets.GITEA_TOKEN }}" | docker login registry.home --username ${{ gitea.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t registry.home/sys-tracker-api:latest .

      - name: Push Docker Image
        run: docker push registry.home/sys-tracker-api:latest
