name: Build
run-name: ${{ gitea.actor }} is running Gitea Actions 🚀

on:
  push:
    branches:
      - main 
env:
  GITEA_INSTANCE_URL: http://gitea.home
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SQLITE_DB_PATH: /data/lab-visor.sqlite

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Python dan Dependensi
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Pastikan Folder Database Ada
      # - name: Ensure Database Directory Exists
      #   run: mkdir -p $(dirname "${{ env.SQLITE_DB_PATH }}")

      - name: Copy alembic.prod.ini to alembic.ini
        run: cp alembic.prod.ini alembic.ini
        
      # Jalankan Alembic Migration
      - name: Run Alembic Migration
        env:
          DATABASE_URL: sqlite:///${{ env.SQLITE_DB_PATH }}
        run: alembic upgrade head

      - name: Use DATABASE_URL from Secret
        run: |
          echo "Database URL: $DATABASE_URL"

      - name: Docker Login
        run: echo "${{ secrets.GITEA_TOKEN }}" | docker login registry.home --username ${{ gitea.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t registry.home/lab-visor:latest .

      - name: Push Docker Image
        run: docker push registry.home/lab-visor:latest
      
      - name: Deploy Docker Image
        run: |
          docker stop lab-visor || true
          docker rm lab-visor || true
          docker run --name lab-visor \
            --restart unless-stopped \
            --network banana \
            --dns 172.18.0.53 \
            -e TZ=Asia/Jakarta \
            -v /proc/uptime:/proc/uptime:ro \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v /home/kirom/lab-visor/data:/code/app/data \
            -d registry.home/lab-visor:latest
