name: Build
run-name: ${{ gitea.actor }} is running Gitea Actions 🚀

on:
  push:
    branches:
      - main 
env:
  GITEA_INSTANCE_URL: http://gitea.home
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use DATABASE_URL from Secret
        run: |
          echo "Database URL: $DATABASE_URL"

      - name: Docker Login
        run: echo "${{ secrets.GITEA_TOKEN }}" | docker login registry.home --username ${{ gitea.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t registry.home/sys-tracker-api:latest .

      - name: Push Docker Image
        run: docker push registry.home/sys-tracker-api:latest
      
      - name: Deploy Docker Image
        run: |
          docker stop sys-tracker-api || true
          docker rm sys-tracker-api || true
          docker run --name sys-tracker-api \
            --restart unless-stopped \
            --network banana \
            --dns 172.18.0.53 \
            -v /proc/uptime:/proc/uptime:ro \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -d registry.home/sys-tracker-api:latest
