"""add theme on category_app

Revision ID: 32fa3f43aae6
Revises: 
Create Date: 2025-02-25 13:50:19.865585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision: str = '32fa3f43aae6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_app', sa.Column('theme', sa.String(100), server_default='primary', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_app', 'theme')
    # ### end Alembic commands ###
