"""add container_name on shortcut_app

Revision ID: 723367806b32
Revises: ef9515117a08
Create Date: 2025-03-06 14:26:12.424558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "723367806b32"
down_revision: Union[str, None] = "ef9515117a08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shortcut_app", sa.Column("container_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shortcut_app", "container_name")
    # ### end Alembic commands ###
