"""add order on category_app

Revision ID: ef9515117a08
Revises: 32fa3f43aae6
Create Date: 2025-02-25 22:10:44.131926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9515117a08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_app', sa.Column('order', sa.Integer(), server_default='99', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_app', 'order')
    # ### end Alembic commands ###
